# Generated by Django 2.2 on 2019-04-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('ddate', models.DateTimeField()),
                ('ggirlnumber', models.IntegerField()),
                ('gboynumber', models.IntegerField()),
                ('isDElete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('scontend', models.CharField(max_length=100)),
                ('isDelete', models.BooleanField(default=False)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Class')),
            ],
        ),
    ]
