# Generated by Django 2.2 on 2019-04-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='isDElete',
            new_name='isDelete',
        ),
    ]
