# Generated by Django 2.2 on 2019-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190422_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default='2019-04-25 02:10:35'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, db_column='lastTime'),
        ),
    ]
